### PR TITLE
Added context-menu for right-click / CTRL+click

### PR DESCRIPTION
**Pull request by Deesen**
#22

context

### CODE REVIEW

**Comment by pmfx** [comment]
Wow that was quick and looks great!
One thing - do we really need "Create new" in context menu? It is already on top.

**Comment by Deesen** [comment]
Yes but do we need the edit-button then too ;-)? I think this way the menu is complete like one would expect, even if "create" is double now.

**Comment by pmfx** [comment]
OK

**Comment by Deesen** [comment]
But probably you are right so maybe it would be best to ask more people about their opinion? @Nicola1971 @fourroses666 @nick0

**Comment by fourroses666** [comment]
Edit on subnav is ok with me. Great work.

**Comment by Nicola1971** [comment]
+1 very nice

**Comment by pmfx** [comment]
Guys, question is: do we need "Create new" link in context menu there?

**Pull request merged**
