### PR TITLE
Issues #19, #20, added lock-icon display

### PR DESCRIPTION
**Pull request by Deesen**

### CODE REVIEW

**Comment by Deesen** [comment]
It should be ready, but the unlock-button needs a JS-function that has not been merged into MODX-core yet, so unlocking an element will not work until then.

**Comment by pmfx** [comment]
Cool, merging.

**Comment by pmfx** [comment]
Just wondering - would it make sense to make this feature (displaying locks) as an option? Disabled by default as it is not fully working. Would it be difficult? What do you think?

**Comment by Deesen** [comment]
Only the unlock-button does not work when you click on it right now because I have renamed a function. The PR is already made, this is the function (yellow marked): https://github.com/modxcms/evolution/pull/921/commits/fa3d734fa5bd41e50ea73f256775ec5a30203ee7#diff-7b112db317309f06e081a6e944445638R137

I think the option is not nessecary.

**Pull request merged**
