### PR TITLE
v1.1.6 #3

### PR DESCRIPTION
**Pull request by Deesen**
- Shift-mouseclick on category collapses/expands all categories
- using localStorage to remember collapsible states :-)

### CODE REVIEW

**Comment by pmfx** [comment]
Shift key works fine! I wonder if dedicated small trigger/button to show/collapse will be useful too from UX perspective. I will try to create something like this.

Issue with remembering states - don't work. Error in console (tested in Firefox):
screenshot_1

**Comment by Deesen** [comment]
Stupid mistake I guess.. does it work now?

**Comment by pmfx** [comment]
Now it works perfectly! I wonder if it would make sense now to have all categories collapsed by default and expand automaticaly only those that were previosly opened. Right now it looks a little strange on reload when categories collapse. Would feel more natural have them all collapsed first and then expand. What do you think @Deesen ?

**Comment by Deesen** [comment]
Hmm but this is contrary to native elements-management where all categories are visible by default. Maybe you want to keep that feel&look at beginning. To close all categories is just a shift-mouseclick... ;-)

**Comment by pmfx** [comment]
You're probably right :)

**Comment by pmfx** [comment]
Merged and I've pushed version number to 1.2.0 (new feature) Good work! :+1:

**Pull request merged**
